name: Update Language Rankings

on:
  schedule:
    # Run every week on Sunday at 00:00 UTC
    - cron: "0 0 * * 0"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-rankings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any dependencies if needed in the future

      - name: Update language analyzer script
        run: |
          curl -o repo_language_analyzer.py https://raw.githubusercontent.com/alessandrobrunoh/alessandrobrunoh/main/repo_language_analyzer.py

      - name: Update config file
        run: |
          curl -o config.json https://raw.githubusercontent.com/alessandrobrunoh/alessandrobrunoh/main/config.json

      - name: Run language analysis
        run: |
          python repo_language_analyzer.py

      - name: Read language ranking file
        id: read_ranking
        run: |
          echo 'data<<EOF' >> $GITHUB_OUTPUT
          cat language_ranking.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Update README with language rankings
        env:
          NEW_RANKING: ${{ steps.read_ranking.outputs.data }}
        run: |
          python3 << EOF
          import re
          import os

          new_ranking = os.environ['NEW_RANKING']

          with open('README.md', 'r') as f:
              content = f.read()

          pattern = r'(?s)## 🔥 Programming Language Rankings.*?(?=## |\Z)'
          new_section = f'## 🔥 Programming Language Rankings\n{new_ranking}'

          if re.search(pattern, content):
              new_content = re.sub(pattern, new_section, content, 1)
          else:
              new_content = content + "\n" + new_section

          with open('README.md', 'w') as f:
              f.write(new_content)
          EOF

      - name: Read language stats file
        id: read_stats
        run: |
          echo 'data<<EOF' >> $GITHUB_OUTPUT
          cat language_ranking.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Update README with language stats
        env:
          LANGUAGE_STATS: ${{ steps.read_stats.outputs.data }}
        run: |
          python3 << EOF
          import re
          import os

          language_stats = os.environ['LANGUAGE_STATS']
          new_section_content = f"<details>\n<summary>Click to see Language Stats</summary>\n\n```json\n{language_stats}\n```\n</details>"

          with open('README.md', 'r') as f:
              content = f.read()

          pattern = r'(?s)## 📊 Language Stats.*?(?=## |\Z)'
          new_section = f'## 📊 Language Stats\n{new_section_content}'

          if re.search(pattern, content):
              new_content = re.sub(pattern, new_section, content, 1)
          else:
              new_content = content + "\n" + new_section

          with open('README.md', 'w') as f:
              f.write(new_content)
          EOF

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md language_ranking.md language_ranking.json
          git commit -m "🔄 Update language rankings - $(date +'%Y-%m-%d')"
          git push

      - name: Create summary
        run: |
          echo "## Language Rankings Updated! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Top 5 Languages:" >> $GITHUB_STEP_SUMMARY
          python3 << EOF
          import json
          with open('language_ranking.json', 'r') as f:
              data = json.load(f)

          for i, (lang, bytes_count) in enumerate(data['ranking'][:5], 1):
              percentage = data['language_percentages'][lang]
              print(f"{i}. **{lang}**: {percentage:.1f}% ({bytes_count:,} bytes)")
          EOF
