name: Update Language Rankings

on:
  schedule:
    # Run every week on Sunday at 00:00 UTC
    - cron: "0 0 * * 0"
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  actions: read

jobs:
  update-rankings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any dependencies if needed in the future

      - name: Update language analyzer script
        run: |
          curl -o repo_language_analyzer.py https://raw.githubusercontent.com/alessandrobrunoh/update-profile-stats-script/refs/heads/main/script.py

      - name: Update config file
        run: |
          curl -o config.json https://raw.githubusercontent.com/alessandrobrunoh/alessandrobrunoh/main/config.json

      - name: Update README with language rankings
        run: |
          export NEW_RANKING=$(cat language_ranking.md)
          python3 << EOF
          import re
          import os

          new_ranking = os.environ.get('NEW_RANKING', '')

          with open('README.md', 'r+') as f:
              content = f.read()
              pattern = r'(?s)## 🔥 Programming Language Rankings.*?(?=## |\Z)'
              new_section = f'## 🔥 Programming Language Rankings\n{new_ranking}'

              if re.search(pattern, content):
                  new_content = re.sub(pattern, new_section, content, 1)
              else:
                  new_content = content + "\n" + new_section

              f.seek(0)
              f.write(new_content)
              f.truncate()
          EOF

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md language_ranking.md language_ranking.json
          git commit -m "🔄 Update language rankings - $(date +'%Y-%m-%d')"
          git fetch origin main
          git rebase origin/main
          git push origin HEAD:main

      - name: Create summary
        run: |
          echo "## Language Rankings Updated! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Top 5 Languages:" >> $GITHUB_STEP_SUMMARY
          python3 << EOF
          import json
          with open('language_ranking.json', 'r') as f:
              data = json.load(f)

          for i, (lang, bytes_count) in enumerate(data['ranking'][:5], 1):
              percentage = data['language_percentages'][lang]
              print(f"{i}. **{lang}**: {percentage:.1f}% ({bytes_count:,} bytes)")
          EOF
